#!/usr/bin/env bash
#this prog exe the following:
#create a file /vas/run/myscript.pid containing the script PID
#display "To infinity and beyond" indefinitely
#display "I hate the kill command" upon receiving a SIGTERM
#display "Y U no love me?!" upon receiving a SIGINT
#deletes the file /vas/run/myscript.pid and terminates upon
#receiving a SIGQUIT or SIGTERM

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
